name: PHPUnit

on:
  push:
  pull_request:

jobs:

  tests:
    name: Tests
    runs-on: Ubuntu-20.04

    strategy:
      matrix:
        include:
          - php: '7.4'
            symfony-require: 4.4.*
          - php: '8.0'
            symfony-require: 5.3.*
          - php: '8.0'
            symfony-require: 6.0.*
            stability: dev
          - php: '8.1'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none

      - name: Configure Composer minimum stability
        if: matrix.stability
        run: composer config minimum-stability ${{ matrix.stability }}

      - name: Install symfony/flex
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require symfony/flex

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        run: composer update --prefer-dist

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
